// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/dalbodeule/hop-gate/ent/domain"
	"github.com/google/uuid"
)

// DomainCreate is the builder for creating a Domain entity.
type DomainCreate struct {
	config
	mutation *DomainMutation
	hooks    []Hook
}

// SetDomain sets the "domain" field.
func (_c *DomainCreate) SetDomain(v string) *DomainCreate {
	_c.mutation.SetDomain(v)
	return _c
}

// SetClientAPIKey sets the "client_api_key" field.
func (_c *DomainCreate) SetClientAPIKey(v string) *DomainCreate {
	_c.mutation.SetClientAPIKey(v)
	return _c
}

// SetMemo sets the "memo" field.
func (_c *DomainCreate) SetMemo(v string) *DomainCreate {
	_c.mutation.SetMemo(v)
	return _c
}

// SetNillableMemo sets the "memo" field if the given value is not nil.
func (_c *DomainCreate) SetNillableMemo(v *string) *DomainCreate {
	if v != nil {
		_c.SetMemo(*v)
	}
	return _c
}

// SetCreatedAt sets the "created_at" field.
func (_c *DomainCreate) SetCreatedAt(v time.Time) *DomainCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *DomainCreate) SetNillableCreatedAt(v *time.Time) *DomainCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *DomainCreate) SetUpdatedAt(v time.Time) *DomainCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *DomainCreate) SetNillableUpdatedAt(v *time.Time) *DomainCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// SetID sets the "id" field.
func (_c *DomainCreate) SetID(v uuid.UUID) *DomainCreate {
	_c.mutation.SetID(v)
	return _c
}

// SetNillableID sets the "id" field if the given value is not nil.
func (_c *DomainCreate) SetNillableID(v *uuid.UUID) *DomainCreate {
	if v != nil {
		_c.SetID(*v)
	}
	return _c
}

// Mutation returns the DomainMutation object of the builder.
func (_c *DomainCreate) Mutation() *DomainMutation {
	return _c.mutation
}

// Save creates the Domain in the database.
func (_c *DomainCreate) Save(ctx context.Context) (*Domain, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *DomainCreate) SaveX(ctx context.Context) *Domain {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *DomainCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *DomainCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *DomainCreate) defaults() {
	if _, ok := _c.mutation.Memo(); !ok {
		v := domain.DefaultMemo
		_c.mutation.SetMemo(v)
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := domain.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		v := domain.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
	if _, ok := _c.mutation.ID(); !ok {
		v := domain.DefaultID()
		_c.mutation.SetID(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *DomainCreate) check() error {
	if _, ok := _c.mutation.Domain(); !ok {
		return &ValidationError{Name: "domain", err: errors.New(`ent: missing required field "Domain.domain"`)}
	}
	if v, ok := _c.mutation.Domain(); ok {
		if err := domain.DomainValidator(v); err != nil {
			return &ValidationError{Name: "domain", err: fmt.Errorf(`ent: validator failed for field "Domain.domain": %w`, err)}
		}
	}
	if _, ok := _c.mutation.ClientAPIKey(); !ok {
		return &ValidationError{Name: "client_api_key", err: errors.New(`ent: missing required field "Domain.client_api_key"`)}
	}
	if v, ok := _c.mutation.ClientAPIKey(); ok {
		if err := domain.ClientAPIKeyValidator(v); err != nil {
			return &ValidationError{Name: "client_api_key", err: fmt.Errorf(`ent: validator failed for field "Domain.client_api_key": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Memo(); !ok {
		return &ValidationError{Name: "memo", err: errors.New(`ent: missing required field "Domain.memo"`)}
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "Domain.created_at"`)}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "Domain.updated_at"`)}
	}
	return nil
}

func (_c *DomainCreate) sqlSave(ctx context.Context) (*Domain, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != nil {
		if id, ok := _spec.ID.Value.(*uuid.UUID); ok {
			_node.ID = *id
		} else if err := _node.ID.Scan(_spec.ID.Value); err != nil {
			return nil, err
		}
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *DomainCreate) createSpec() (*Domain, *sqlgraph.CreateSpec) {
	var (
		_node = &Domain{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(domain.Table, sqlgraph.NewFieldSpec(domain.FieldID, field.TypeUUID))
	)
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = &id
	}
	if value, ok := _c.mutation.Domain(); ok {
		_spec.SetField(domain.FieldDomain, field.TypeString, value)
		_node.Domain = value
	}
	if value, ok := _c.mutation.ClientAPIKey(); ok {
		_spec.SetField(domain.FieldClientAPIKey, field.TypeString, value)
		_node.ClientAPIKey = value
	}
	if value, ok := _c.mutation.Memo(); ok {
		_spec.SetField(domain.FieldMemo, field.TypeString, value)
		_node.Memo = value
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(domain.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(domain.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	return _node, _spec
}

// DomainCreateBulk is the builder for creating many Domain entities in bulk.
type DomainCreateBulk struct {
	config
	err      error
	builders []*DomainCreate
}

// Save creates the Domain entities in the database.
func (_c *DomainCreateBulk) Save(ctx context.Context) ([]*Domain, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*Domain, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*DomainMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *DomainCreateBulk) SaveX(ctx context.Context) []*Domain {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *DomainCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *DomainCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
